apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-mark
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: jenkins-demo-mark
  template:
    metadata:
      labels:
        app: jenkins-demo-mark
    spec:
      containers:
        - name: jenkins-demo-mark
          image: homemcsese/jenkins-demo:latest
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 30
